using System;

[Serializable]
public enum GameEventType {
  BANK_DEPOSIT,
  BANK_WITHDRAWAL,
  PLAYER_TAGGED,
  DISTRICT_CONQUERED,
  TRADEPOST_LEGAL_SALE,
  TRADEPOST_LEGAL_PURCHASE,
  TRADEPOST_ILLEGAL_SALE,
  TRADEPOST_ILLEGAL_PURCHASE,
  TREASURY_WITHDRAWAL,
  TRADEPOST_ALL_SALE,
  TREASURY_ROBBERY

}